### ISSUE TITLE
fix indents

### ISSUE THREAD

**Issue by greglinch** [lexinal/About-Me#2]
These lines appear to be indented one extra space:
https://github.com/lexinal/About-Me/blob/master/About%20Me.html#L12-L13

This is sibling to the `h1` tag and should be un-indented by one level:
https://github.com/lexinal/About-Me/blob/master/About%20Me.html#L9

Also, it looks like that `div` is never closed. It should end be closed before the hobbies `div`.

This should be indented to be consistent with the others:
https://github.com/lexinal/About-Me/blob/master/About%20me.css#L17

**Comment by lexinal** [comment]
fixed. Thanks! I have a question about div, would you recommend there be a div for every section of a page?
