### ISSUE TITLE
use p tags around general text

### ISSUE THREAD

**Issue by greglinch** [lexinal/About-Me#3]
For example, each line of text in this highlighted area should have its own `p` tag:

https://github.com/lexinal/About-Me/blob/master/About%20Me.html#L13-L16

It's also better to use `p` tags instead of `br` so you can control the styling, so please remove the `br` tags after you've made the `p` tag updates.

**Comment by lexinal** [comment]
Fixed. Another question, could a <p> tag go before the <div> tag seen in the ones you've highlighted?
